const supabaseClient=window.supabase.createClient(window.BZ_SUPABASE_URL,window.BZ_SUPABASE_KEY);
let products=[],cart=JSON.parse(localStorage.getItem("bz_cart")||"[]");
const fallbackProducts=[{name:"VECTOR",product_type:"plugin",short_description:"Synthesis / FX",price_cents:7900,slug:"vector"},{name:"VOID SIGNALS",product_type:"sample",short_description:"Cinematic Samples",price_cents:2900,slug:"void-signals"},{name:"MOTION",product_type:"plugin",short_description:"Dynamics / FX",price_cents:4900,slug:"motion"},{name:"NIGHT DRIVE",product_type:"sample",short_description:"Electronic Loops",price_cents:2400,slug:"night-drive"},{name:"ORBIT",product_type:"plugin",short_description:"Modular Instrument",price_cents:8900,slug:"orbit"},{name:"RAW ROOM",product_type:"sample",short_description:"Drums / Textures",price_cents:1900,slug:"raw-room"}];
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n/100);
async function loadProducts(){const {data,error}=await supabaseClient.from("products").select("*").eq("is_published",true).order("created_at",{ascending:false});products=error||!data?.length?fallbackProducts:data;render(products)}
function render(list){document.querySelector("#productGrid").innerHTML=list.map(p=>`<article class="product"><div class="product-art"><span>BZ</span><em>${p.product_type}</em></div><div class="product-info"><div><small>${p.short_description||p.product_type}</small><h3>${p.name}</h3></div><div><div class="price">${money(p.price_cents)}</div><button class="line-btn" onclick="addCart('${p.slug}')">ADD +</button></div></div></article>`).join("");document.querySelector("#sampleStrip").innerHTML=list.filter(p=>p.product_type==="sample").map(p=>`<div class="sample"><strong>${p.name}</strong><span>${p.short_description||"SAMPLE"} · ${money(p.price_cents)}</span></div>`).join("")}
function filterProducts(type){render(type==="all"?products:products.filter(p=>p.product_type===type));document.querySelector("#shop").scrollIntoView({behavior:"smooth"})}
function addCart(slug){const p=products.find(x=>x.slug===slug);if(!p)return;cart.push(p);localStorage.setItem("bz_cart",JSON.stringify(cart));updateCartCount();openModal(`<p class="eyebrow">ADDED TO BAG</p><h2>${p.name}.</h2><p style="color:#888">Your item is ready for checkout.</p><button class="primary" onclick="closeModal()">Continue shopping ↗</button>`)}
function updateCartCount(){document.querySelector("#cartCount").textContent=cart.length}
function openModal(html){document.querySelector("#modalContent").innerHTML=html;document.querySelector("#modal").classList.remove("hidden")}
function closeModal(){document.querySelector("#modal").classList.add("hidden")}
async function openAccount(){const {data:{user}}=await supabaseClient.auth.getUser();openModal(user?`<p class="eyebrow">BZ ACCOUNT</p><h2>${user.email}</h2><p style="color:#888">Your account is active.</p><button class="outline" onclick="signOut()">SIGN OUT</button>`:`<p class="eyebrow">BZ ACCOUNT</p><h2>Join BZ Audio.</h2><input id="email" type="email" placeholder="Email" style="width:100%;padding:16px;background:#181818;border:1px solid #333;color:white;margin:8px 0"><input id="password" type="password" placeholder="Password" style="width:100%;padding:16px;background:#181818;border:1px solid #333;color:white;margin:8px 0"><button class="primary" onclick="signUp()">CREATE ACCOUNT</button><button class="secondary" onclick="signIn()">SIGN IN</button>`)}
async function signUp(){const email=document.querySelector("#email").value,password=document.querySelector("#password").value;const {error}=await supabaseClient.auth.signUp({email,password});openModal(error?`<h2>Account error.</h2><p>${error.message}</p>`:"<h2>Check your email.</h2><p>Confirm your email to finish creating your BZ Account.</p>")}
async function signIn(){const email=document.querySelector("#email").value,password=document.querySelector("#password").value;const {error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)openModal(`<h2>Sign-in error.</h2><p>${error.message}</p>`);else closeModal()}
async function signOut(){await supabaseClient.auth.signOut();closeModal()}
async function openLibrary(){const {data:{user}}=await supabaseClient.auth.getUser();if(!user){openAccount();return}const {data}=await supabaseClient.from("licenses").select("license_key,status,products(name,product_type,version)").eq("user_id",user.id);openModal(`<p class="eyebrow">BZ LIBRARY</p><h2>Your collection.</h2>${data?.length?data.map(x=>`<div class="library-row"><strong>${x.products?.name||"Product"}</strong><span>${x.status} · ${x.license_key}</span></div>`).join(""):"<p style='color:#888'>Your purchased products will appear here.</p>"}`)}
document.querySelector("#adminBtn").onclick=async()=>{const {data:{user}}=await supabaseClient.auth.getUser();if(!user){openAccount();return}if(user.app_metadata?.role!=="admin"){openModal("<h2>Admin access required.</h2><p style='color:#888'>This account does not have administrator permissions.</p>");return}openModal(`<p class="eyebrow">BZ AUDIO / COMMAND CENTER</p><h2>Admin.</h2><p style="color:#888;line-height:1.7">Products, files, collections, discounts, homepage content, orders, customers and analytics are backed by Supabase.</p><div class="admin-grid"><button onclick="adminProducts()">Products</button><button onclick="openLibrary()">Library</button><button>＋ Upload Sample Pack</button><button>＋ Add Plugin</button><button>＋ Create Collection</button><button>＋ Create Discount</button><button>＋ Add Homepage Section</button><button>Orders & Customers</button><button>Analytics</button></div>`)}
async function adminProducts(){const {data}=await supabaseClient.from("products").select("*").order("created_at",{ascending:false});openModal(`<p class="eyebrow">COMMAND CENTER / STORE</p><h2>Products.</h2><div class="admin-grid">${data?.map(p=>`<button onclick="togglePublish('${p.id}',${!p.is_published})">${p.is_published?"●":"○"} ${p.name}</button>`).join("")||""}</div>`)}
async function togglePublish(id,value){await supabaseClient.from("products").update({is_published:value}).eq("id",id);adminProducts();loadProducts()}
document.querySelector("#searchBtn").onclick=()=>openModal(`<p class="eyebrow">SEARCH BZ AUDIO</p><h2>Find your sound.</h2><input id="searchInput" autofocus placeholder="Search plugins, samples..." style="width:100%;padding:16px;background:#181818;border:1px solid #333;color:white" oninput="searchProducts(this.value)">`);
function searchProducts(q){const v=q.toLowerCase();render(products.filter(p=>(p.name+" "+(p.short_description||"")+" "+p.product_type).toLowerCase().includes(v)))}
document.querySelector("#cartBtn").onclick=()=>openModal(`<p class="eyebrow">YOUR BAG</p><h2>${cart.length?cart.length+" item"+(cart.length>1?"s":""):"Empty"}.</h2><p style="color:#888">${cart.length?"Stripe checkout will connect here once your Stripe account is connected.":"Add products from the store to begin."}</p>${cart.length?`<button class="outline" onclick="cart=[];localStorage.removeItem('bz_cart');updateCartCount();closeModal()">CLEAR BAG</button>`:""}`);
document.querySelector(".logo").addEventListener("click",e=>e.preventDefault());updateCartCount();loadProducts();
